=== Hermdroid/book-code/eXist-Book-xar/book-browser/examples-contents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="eXistBookExamplesContents">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Title" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Title of the page</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" name="Description" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Optional additional description (or page-wide remarks)</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Example">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Title" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>Title for this example</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element minOccurs="0" name="Description" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>Optional additional description or remark for this example</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="AdditionalSource">
                                <xs:annotation>
                                    <xs:documentation>Optional link to view the source of an additional resource (e.g. an XML file referenced)</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:attribute name="href" type="xs:string" use="required">
                                        <xs:annotation>
                                            <xs:documentation>Name of the resource. Must be relative to the current collection.</xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="href" type="xs:string" use="required">
                            <xs:annotation>
                                <xs:documentation>Name of the resource to link to. Must be relative to the current collection.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute default="false" name="rest" type="xs:boolean">
                            <xs:annotation>
                                <xs:documentation>Whether or not this resource is linked through rest (URL starts with /exist/rest/db/...) or as an application resource (URL starts with /exist/apps/...).</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute default="true" name="show-source" type="xs:boolean">
                            <xs:annotation>
                                <xs:documentation>Whether or not a link to view the source of this resource is generated</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="chapter" type="xs:integer" use="required">
                <xs:annotation>
                    <xs:documentation>Chapter or section number of this collection. Used for sorting.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Hermdroid/book-code/chapters/working-with-the-database/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="4">
  <Title>Working with the database</Title>
  <!-- -->
  <Example href="show-uri-encoding.xq">
    <Title>Show the URI encoding of a name</Title>
  </Example>
  <!-- -->
  <Example href="show-collection-use.xq">
    <Title>Show the usage of the collection function</Title>
  </Example>
  <!-- -->
  <Example href="" rest="true" show-source="false">
    <Title>Example of a GET REST request on a collection</Title>
  </Example>
  <!-- -->
  <Example href="put-request.xq">
    <Title>Store a file in the database using a PUT request</Title>
    <Description>The file will be stored in /db/apps/exist-book/data/put-example.xml</Description>
    <AdditionalSource href="../data/put-example.xml"/>
  </Example>
  <!-- -->
  <Example href="delete-request.xq">
    <Title>Delete a file in the database using a DELETE request</Title>
    <Description>The file deleted is the same file as used in the PUT example:
      /db/apps/exist-book/data/put-example.xml</Description>
  </Example>
  <!-- -->
  <Example href="post-request.xq">
    <Title>Fire an extended query POST request at the database</Title>
  </Example>
  <!-- -->
  <Example href="update-document-1.xq">
    <Title>Update a document using eXistXQuery update extensions</Title>
    <Description>The file changed is: /db/apps/exist-book/data/update-resource.xml</Description>
    <AdditionalSource href="../data/update-resource.xml"/>
  </Example>
  <!-- -->
  <!-- -->
  <Example href="traverse.xq">
    <Title>Traverse the book examples using calls from the xmldb extension module</Title>
  </Example>
  <!-- -->
</eXistBookExamplesContents>

=== Hermdroid/book-code/chapters/getting-started/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="2">
    <Title>Getting started</Title>
  <!-- -->
    <Example href="xml-example.xml" rest="true">
        <Title>Access an XML file through the REST interface</Title>
    </Example>
  <!-- -->
    <Example href="xml-example.xml?_query=//Item[1]" rest="true" show-source="false ">
        <Title>Query an XML file (//Item[1]) through the REST interface</Title>
    </Example>
  <!-- -->
    <Example href="hello-world-1.xq">
        <Title>Hello XQuery World - XML result</Title>
    </Example>
  <!-- -->
    <Example href="hello-world-2.xq">
        <Title>Hello XQuery World - HTML result</Title>
    </Example>
  <!-- -->
    <Example href="transform-xsl.xq">
        <Title>Hello XSLT from within XQuery</Title>
        <AdditionalSource href="convert-items.xslt"/>
    </Example>
  <!-- -->
    <Example href="xinclude-envelope.xml">
        <Title>XML document with embedded XInclude instructions</Title>
        <AdditionalSource href="xinclude-content.xml"/>
        <AdditionalSource href="hello-world-1.xq"/>
    </Example>
  <!-- -->
    <Example href="hello-xforms.html" show-source="false">
        <Title>Hello XForms</Title>
        <Description>Remark: Because this is a HTML form, viewing the source won't tell you much, the
      browser will try to render it anyway...</Description>
        <AdditionalSource href="hello-xforms-submit.xq"/>
    </Example>
  <!-- -->
</eXistBookExamplesContents>

=== Hermdroid/book-code/chapters/building-applications/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="8">
  <Title>Building Applications</Title>
  <!-- -->
  <Example href="mini-application/" show-source="false">
    <Title>The URL rewriting demo mini application</Title>
    <AdditionalSource href="mini-application/controller.xql"/>
    <AdditionalSource href="mini-application/home.xq"/>
    <AdditionalSource href="mini-application/hello.xq"/>
  </Example>
  <!-- -->
  <Example href="show-controller-variables/" show-source="false">
    <Title>Show the controller variables</Title>
    <AdditionalSource href="show-controller-variables/controller.xql"/>
    <AdditionalSource href="show-controller-variables/show-controller-variables.xq"/>
  </Example>
  <!-- -->
  <Example href="views/" show-source="false">
    <Title>Examples for the advanced URL controlling</Title>
    <AdditionalSource href="views/controller.xql"/>
    <AdditionalSource href="views/createmodel.xq"/>
    <AdditionalSource href="views/home.xq"/>
    <AdditionalSource href="views/xslt/view1.xslt"/>
    <AdditionalSource href="views/xslt/view2a.xslt"/>
    <AdditionalSource href="views/xslt/view2b.xslt"/>
  </Example>
  <!-- -->
  <Example href="upload/upload.xq">
    <Title>Upload a file to the database</Title>
    <Description>The file will be stored in /db/apps/exist-book/data</Description>
    <AdditionalSource href="upload/upload-process.xq"/>
  </Example>
  <!-- -->
  <Example href="download.xq">
    <Title>Download an XML file</Title>
  </Example>
  <!-- -->
  <Example href="restxq/">
    <Title>RESTXQ Examples</Title>
    <AdditionalSource href="restxq/restxq-example-1.xqm"/>
    <AdditionalSource href="restxq/restxq-example-2.xqm"/>
    <AdditionalSource href="restxq/restxq-example-3.xqm"/>
    <AdditionalSource href="restxq/restxq-example-4.xqm"/>
    <AdditionalSource href="restxq/restxq-example-5.xqm"/>
    <AdditionalSource href="restxq/restxq-example-6.xqm"/>
    <AdditionalSource href="restxq/restxq-example-7.xqm"/>
  </Example>
  <!-- -->
</eXistBookExamplesContents>

=== Hermdroid/book-code/chapters/indexing/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="10">
  <Title>Basic and Text Indexing</Title>
  <!-- -->
  <Example href="test-indexes.xq">
    <Title>Test searches with and without indexes</Title>
    <AdditionalSource href="data/Encyclopedia.xml"/>
    <AdditionalSource href="data/Encyclopedia-ALT.xml"/>
    <AdditionalSource href="collection.xconf"/>
  </Example>
  <!-- -->
  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <!-- -->
  <Example href="search-demo.xq">
    <Title>Full-text search</Title>
    <AdditionalSource href="search-demo-result.xq"/>
    <AdditionalSource href="data/Encyclopedia.xml"/>
    <AdditionalSource href="collection.xconf"/>
  </Example>
  <!-- -->
</eXistBookExamplesContents>

=== Hermdroid/book-code/xml-examples-xar/building-applications/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="8">
    <Title>Building Applications</Title>
  <!-- -->
    <Example href="mini-application/" show-source="false">
        <Title>The URL rewriting demo mini application</Title>
        <AdditionalSource href="mini-application/controller.xql"/>
        <AdditionalSource href="mini-application/home.xql"/>
        <AdditionalSource href="mini-application/hello.xql"/>
    </Example>
  <!-- -->
    <Example href="show-controller-variables/" show-source="false">
        <Title>Show the controller variables</Title>
        <AdditionalSource href="show-controller-variables/controller.xql"/>
        <AdditionalSource href="show-controller-variables/show-controller-variables.xql"/>
    </Example>
  <!-- -->
    <Example href="views/" show-source="false">
        <Title>Examples for the advanced URL controlling</Title>
        <AdditionalSource href="views/controller.xql"/>
        <AdditionalSource href="views/createmodel.xql"/>
        <AdditionalSource href="views/home.xql"/>
        <AdditionalSource href="views/xsl/view1.xsl"/>
        <AdditionalSource href="views/xsl/view2a.xsl"/>
        <AdditionalSource href="views/xsl/view2b.xsl"/>
    </Example>
  <!-- -->
    <Example href="upload/upload.xql">
        <Title>Upload a file to the database</Title>
        <Description>The file will be stored in /db/apps/eXist-book/data</Description>
        <AdditionalSource href="upload/upload-process.xql"/>
    </Example>
  <!-- -->
    <Example href="download.xql">
        <Title>Download an XML file</Title>
    </Example>
  <!-- -->
</eXistBookExamplesContents>

=== Hermdroid/book-code/chapters/extension-modules/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="6">
    <Title>Extension Modules</Title>
    <Description>If any of these examples results in a namespace error, edit $EXIST_HOME/conf.xml, enable the
    module (make sure the &lt;module ...&gt; element for it is not commented out) and restart
    eXist.</Description>
  <!-- -->
    <Example href="cache-example.xq">
        <Title>Example of using the global cache module</Title>
    </Example>
  <!-- -->
    <Example href="demo-zip.xq">
        <Title>Example creating a zip file with eXist</Title>
        <Description>Make sure you have a directory /Test on your disk, otherwise this script will fail! 
      When this script starts, it will aks you to login: this is because it needs admin priviliges to 
      write to the file system. Please login as admin and continue. The output will be written to /test/compression-test.zip</Description>
    </Example>
  <!-- -->
    <Example href="test-contentextraction.xq">
        <Title>Show extracted content from a chapter of the Exist book</Title>
        <Description>Although this script outputs XML, on some browsers it will show up as a html page because it contains html elements and the browser arrogantly ignores the MIME type...</Description>
    </Example>
  <!-- -->
    <Example href="test-http-client.xq">
        <Title>Get the contents of /db using the the EXpath http client and eXist's REST capabilities.</Title>
    </Example>
  <!-- -->
    <Example href="test-image.xq">
        <Title>Showing some properties of an image acquired through the image module.</Title>
    </Example>
  <!-- -->
    <Example href="send-mail.xq">
        <Title>Sending mail through the mail extension module</Title>
        <AdditionalSource href="do-send-mail.xq"/>
    </Example>
  <!-- -->
    <Example href="start-scheduled-job.xq">
        <Title>Start a scheduled job that writes a  number of times to data/schedule-log.xml</Title>
        <Description>When this script starts, it will aks you to login: this is because it needs admin priviliges.</Description>
        <AdditionalSource href="do-scheduled-job.xq"/>
        <AdditionalSource href="../data/schedule-log.xml"/>
    </Example>
  <!-- -->
    <Example href="sort-example.xq">
        <Title>Sort a list of nodes using the sort module</Title>
        <AdditionalSource href="sort-node-set.xml"/>
    </Example>
  <!-- -->
</eXistBookExamplesContents>

=== Hermdroid/book-code/eXist-Book-xar/other-xml-technologies/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="9">
    <Title>Other XML Technologies</Title>
  <!-- -->
    <Example href="get-xslt-info.xql">
        <Title>XSLT: Get information about the XSLT processor using an embedded stylesheet</Title>
    </Example>
  <!-- -->
    <Example href="xslt-parameters.xql">
        <Title>Passing parameters to an XSLT stylesheet</Title>
        <AdditionalSource href="parameters.xslt"/>
    </Example>
  <!-- -->
    <Example href="xinclude-examples.xml">
        <Title>Some examples of the XInclude capabilities</Title>
        <AdditionalSource href="xinclude-input.xml"/>
        <AdditionalSource href="xinclude-xquery.xql"/>
    </Example>
  <!-- -->
    <Example href="validate.xql">
        <Title>Perform some validations</Title>
        <AdditionalSource href="simple.xsd"/>
        <AdditionalSource href="simple-xml-valid.xml"/>
        <AdditionalSource href="simple-xml-invalid.xml"/>
    </Example>
  <!-- -->
    <Example href="collations.xql">
        <Title>Example of sorting according to a collation</Title>
    </Example>
  <!-- -->
    <Example href="do-xsl-fo.xql">
        <Title>Example of an XSL-FO transformation</Title>
        <AdditionalSource href="fop-readme.xml"/>
    </Example>
</eXistBookExamplesContents>

=== Hermdroid/book-code/chapters/other-xml-technologies/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="9">
    <Title>Other XML Technologies</Title>
    <!-- -->
    <Example href="get-xslt-info.xq">
        <Title>XSLT: Get information about the XSLT processor using an embedded stylesheet</Title>
    </Example>
    <!-- -->
    <Example href="xslt-parameters.xq">
        <Title>Passing parameters to an XSLT stylesheet</Title>
        <AdditionalSource href="parameters.xslt"/>
    </Example>
    <!-- -->
    <Example href="xinclude-examples.xml">
        <Title>Some examples of the XInclude capabilities</Title>
        <AdditionalSource href="xinclude-input.xml"/>
        <AdditionalSource href="xinclude-xquery.xq"/>
    </Example>
    <!-- -->
    <Example href="validate.xq">
        <Title>Perform some validations</Title>
        <AdditionalSource href="simple.xsd"/>
        <AdditionalSource href="simple-xml-valid.xml"/>
        <AdditionalSource href="simple-xml-invalid.xml"/>
    </Example>
    <!-- -->
    <Example href="collations.xq">
        <Title>Example of sorting according to a collation</Title>
    </Example>
    <!-- -->
    <Example href="do-xsl-fo.xq">
        <Title>Example of an XSL-FO transformation</Title>
        <AdditionalSource href="fop-readme.xml"/>
    </Example>
    <!-- -->
    <Example href="better-form/test-xform.xhtml">
        <title>BetterForm: Address XForm Example</title>
    </Example>
    <!-- -->
    <Example href="xslt-forms/test-xform.xhtml">
        <title>XSLTForms: Address XForm Example</title>
    </Example>
</eXistBookExamplesContents>
