=== Hermdroid/book-code/eXist-Book-xar/book-browser/examples-contents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="eXistBookExamplesContents">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Title" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Title of the page</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" name="Description" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Optional additional description (or page-wide remarks)</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Example">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Title" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>Title for this example</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element minOccurs="0" name="Description" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>Optional additional description or remark for this example</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="AdditionalSource">
                                <xs:annotation>
                                    <xs:documentation>Optional link to view the source of an additional resource (e.g. an XML file referenced)</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:attribute name="href" type="xs:string" use="required">
                                        <xs:annotation>
                                            <xs:documentation>Name of the resource. Must be relative to the current collection.</xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="href" type="xs:string" use="required">
                            <xs:annotation>
                                <xs:documentation>Name of the resource to link to. Must be relative to the current collection.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute default="false" name="rest" type="xs:boolean">
                            <xs:annotation>
                                <xs:documentation>Whether or not this resource is linked through rest (URL starts with /exist/rest/db/...) or as an application resource (URL starts with /exist/apps/...).</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute default="true" name="show-source" type="xs:boolean">
                            <xs:annotation>
                                <xs:documentation>Whether or not a link to view the source of this resource is generated</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="chapter" type="xs:integer" use="required">
                <xs:annotation>
                    <xs:documentation>Chapter or section number of this collection. Used for sorting.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Hermdroid/book-code/xml-examples-xar/working-with-the-database/examples-contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<eXistBookExamplesContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../book-browser/examples-contents.xsd" chapter="4">
    <Title>Working with the database</Title>
  <!-- -->
    <Example href="show-uri-encoding.xql">
        <Title>Show the URI encoding of a name</Title>
    </Example>
  <!-- -->
    <Example href="show-collection-use.xql">
        <Title>Show the usage of the collection function</Title>
    </Example>
  <!-- -->
    <Example href="" rest="true" show-source="false">
        <Title>Example of a GET REST request on a collection</Title>
    </Example>
  <!-- -->
    <Example href="put-request.xql">
        <Title>Store a file in the database using a PUT request</Title>
        <Description>The file will be stored in /db/apps/eXist-book/data/put-example.xml</Description>
        <AdditionalSource href="../data/put-example.xml"/>
    </Example>
  <!-- -->
    <Example href="delete-request.xql">
        <Title>Delete a file in the database using a DELETE request</Title>
        <Description>The file deleted is the same file as used in the PUT example: /db/apps/eXist-book/data/put-example.xml</Description>
    </Example>
  <!-- -->
    <Example href="post-request.xql">
        <Title>Fire an extended query POST request at the database</Title>
    </Example>
  <!-- -->
    <Example href="update-document-1.xql">
        <Title>Update a document using eXistXQuery update extensions</Title>
        <Description>The file changed is: /db/apps/eXist-book/data/update-resource.xml</Description>
        <AdditionalSource href="../data/update-resource.xml"/>
    </Example>
  <!-- -->
  <!-- -->
    <Example href="traverse.xql">
        <Title>Traverse the book examples using calls from the xmldb extension module</Title>
    </Example>
  <!-- -->
</eXistBookExamplesContents>
